//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Custom
{
    [Serializable]
    public class VisMeaMsg : Message
    {
        public const string k_RosMessageName = "custom_msgs/VisMea";
        public override string RosMessageName => k_RosMessageName;

        //  Visual Measurement f of 4 feature points as viewed from a camera
        //  FP1
        public float fp1_x;
        public float fp1_y;
        //  FP2
        public float fp2_x;
        public float fp2_y;
        //  FP3
        public float fp3_x;
        public float fp3_y;
        //  FP4
        public float fp4_x;
        public float fp4_y;

        public VisMeaMsg()
        {
            this.fp1_x = 0.0f;
            this.fp1_y = 0.0f;
            this.fp2_x = 0.0f;
            this.fp2_y = 0.0f;
            this.fp3_x = 0.0f;
            this.fp3_y = 0.0f;
            this.fp4_x = 0.0f;
            this.fp4_y = 0.0f;
        }

        public VisMeaMsg(float fp1_x, float fp1_y, float fp2_x, float fp2_y, float fp3_x, float fp3_y, float fp4_x, float fp4_y)
        {
            this.fp1_x = fp1_x;
            this.fp1_y = fp1_y;
            this.fp2_x = fp2_x;
            this.fp2_y = fp2_y;
            this.fp3_x = fp3_x;
            this.fp3_y = fp3_y;
            this.fp4_x = fp4_x;
            this.fp4_y = fp4_y;
        }

        public static VisMeaMsg Deserialize(MessageDeserializer deserializer) => new VisMeaMsg(deserializer);

        private VisMeaMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.fp1_x);
            deserializer.Read(out this.fp1_y);
            deserializer.Read(out this.fp2_x);
            deserializer.Read(out this.fp2_y);
            deserializer.Read(out this.fp3_x);
            deserializer.Read(out this.fp3_y);
            deserializer.Read(out this.fp4_x);
            deserializer.Read(out this.fp4_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.fp1_x);
            serializer.Write(this.fp1_y);
            serializer.Write(this.fp2_x);
            serializer.Write(this.fp2_y);
            serializer.Write(this.fp3_x);
            serializer.Write(this.fp3_y);
            serializer.Write(this.fp4_x);
            serializer.Write(this.fp4_y);
        }

        public override string ToString()
        {
            return "VisMeaMsg: " +
            "\nfp1_x: " + fp1_x.ToString() +
            "\nfp1_y: " + fp1_y.ToString() +
            "\nfp2_x: " + fp2_x.ToString() +
            "\nfp2_y: " + fp2_y.ToString() +
            "\nfp3_x: " + fp3_x.ToString() +
            "\nfp3_y: " + fp3_y.ToString() +
            "\nfp4_x: " + fp4_x.ToString() +
            "\nfp4_y: " + fp4_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
